# Generated by Django 4.1.2 on 2022-10-25 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("text", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_sample_url", models.URLField(blank=True, max_length=400)),
                (
                    "user_video_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.user_post"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("day_of_birth", models.DateTimeField(blank=True)),
                ("country", models.TextField(blank=True, max_length=30)),
                ("phone_number", models.TextField(blank=True, max_length=16)),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("profile_pic_url", models.URLField(blank=True, max_length=400)),
                ("about", models.TextField(null=True)),
                ("friend", models.ManyToManyField(blank=True, to="base.user_profile")),
            ],
        ),
        migrations.AddField(
            model_name="user_post",
            name="profile_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.user_profile"
            ),
        ),
        migrations.CreateModel(
            name="Text_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(null=True)),
                (
                    "user_post_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="base.user_post"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post_like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.user_post"
                    ),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.user_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post_comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("text", models.TextField(null=True)),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.user_post"
                    ),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.user_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photo_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_sample_url", models.URLField(blank=True, max_length=400)),
                (
                    "user_post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.user_post"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Friendship_request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_state", models.BooleanField(default=True)),
                (
                    "receiver_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_receiver_id",
                        to="base.user_profile",
                    ),
                ),
                (
                    "sender_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_sender_id",
                        to="base.user_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follow_request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_state", models.BooleanField(default=True)),
                (
                    "receiver_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_receiver_id",
                        to="base.user_profile",
                    ),
                ),
                (
                    "sender_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_sender_id",
                        to="base.user_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Audio_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_sample_url", models.URLField(blank=True, max_length=400)),
                (
                    "user_audio_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.user_post"
                    ),
                ),
            ],
        ),
    ]
