# Generated by Django 4.1.2 on 2022-10-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_profile",
            name="uuid",
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
