# Generated by Django 4.1.2 on 2022-10-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_user_profile_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profile",
            name="day_of_birth",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
